

# Functions and constants -------------------------------------------------

sq <- function(...) sQuote(paste0(...),FALSE) # single quote

dq <- function(...) dQuote(paste0(...),FALSE) # double quote

JAF_Compendium_Index <-
  '
| CompendiumNum  | JAF_KEY                  |
|----------------|--------------------------|
| 1              | PA1.O1.                  |
| 1              | PA1.S1.M                 |
| 1              | PA1.S1.F                 |
| 1              | PA1.S2.                  |
| 1              | PA1.S3.                  |
| 1              | PA1.S4.                  |
| 1              | PA1.S5.                  |
| 1              | PA1.C1.                  |
| 1              | PA1.C2.15-64             |
| 1              | PA1.C2.15-19             |
| 1              | PA1.C2.15-24             |
| 1              | PA1.C2.50-59             |
| 1              | PA1.C2.60-64             |
| 1              | PA1.C2.65-69             |
| 1              | PA1.C2.15-64.M           |
| 1              | PA1.C2.15-19.M           |
| 1              | PA1.C2.15-24.M           |
| 1              | PA1.C2.50-59.M           |
| 1              | PA1.C2.60-64.M           |
| 1              | PA1.C2.M                 |
| 1              | PA1.C2.15-64.F           |
| 1              | PA1.C2.15-19.F           |
| 1              | PA1.C2.15-24.F           |
| 1              | PA1.C2.50-59.F           |
| 1              | PA1.C2.60-64.F           |
| 1              | PA1.C2.65-69.F           |
| 1              | PA1.C3.T                 |
| 1              | PA1.C3.15-64             |
| 1              | PA1.C3.15-19             |
| 1              | PA1.C3.15-24             |
| 1              | PA1.C3.50-59             |
| 1              | PA1.C3.60-64             |
| 1              | PA1.C3.65-69             |
| 1              | PA1.C3.15-64.M           |
| 1              | PA1.C3.15-19.M           |
| 1              | PA1.C3.15-24.M           |
| 1              | PA1.C3.50-59.M           |
| 1              | PA1.C3.60-64.M           |
| 1              | PA1.C3.65-69.M           |
| 1              | PA1.C3.15-64.F           |
| 1              | PA1.C3.15-19.F           |
| 1              | PA1.C3.15-24.F           |
| 1              | PA1.C3.50-59.F           |
| 1              | PA1.C3.60-64.F           |
| 1              | PA1.C3.65-69.F           |
| 1              | PA1.C3.NAT               |
| 1              | PA1.C3.EU27_2020         |
| 1              | PA1.C3.nonEU27_2020      |
| 1              | PA1.C3.low               |
| 1              | PA1.C3.med               |
| 1              | PA1.C3.high              |
| 1              | PA1.C4.T                 |
| 1              | PA1.C4.15-64             |
| 1              | PA1.C4.15-19             |
| 1              | PA1.C4.15-24             |
| 1              | PA1.C4.50-59             |
| 1              | PA1.C4.60-64             |
| 1              | PA1.C4.65-69             |
| 1              | PA1.C4.15-64.M           |
| 1              | PA1.C4.15-19.M           |
| 1              | PA1.C4.15-24.M           |
| 1              | PA1.C4.50-59.M           |
| 1              | PA1.C4.60-64.M           |
| 1              | PA1.C4.65-69.M           |
| 1              | PA1.C4.15-64.F           |
| 1              | PA1.C4.15-19.F           |
| 1              | PA1.C4.15-24.F           |
| 1              | PA1.C4.50-59.F           |
| 1              | PA1.C4.60-64.F           |
| 1              | PA1.C4.65-69.F           |
| 1              | PA1.C4.NAT               |
| 1              | PA1.C4.EU27_2020         |
| 1              | PA1.C4.nonEU27_2020      |
| 1              | PA1.C4.low               |
| 1              | PA1.C4.med               |
| 1              | PA1.C4.high              |
| 2              | PA1b.O1.                 |
| 2              | PA1b.O1.n.               |
| 2              | PA1b.S1.M                |
| 2              | PA1b.S1.F                |
| 2              | PA1b.S2.                 |
| 2              | PA1b.S3.                 |
| 2              | PA1b.S4.                 |
| 2              | PA1b.S5.                 |
| 2              | PA1b.S6.                 |
| 2              | PA1b.S1.n.M              |
| 2              | PA1b.S1.n.F              |
| 2              | PA1b.S5.n.               |
| 2              | PA1b.S6.n.               |
| 2              | PA1b.C1.Y15-19.T         |
| 2              | PA1b.C1.Y15-19.M         |
| 2              | PA1b.C1.Y15-19.F         |
| 2              | PA1b.C1.Y20-24.T         |
| 2              | PA1b.C1.Y20-24.M         |
| 2              | PA1b.C1.Y20-24.F         |
| 2              | PA1b.C1.Y25-29.T         |
| 2              | PA1b.C1.Y25-29.M         |
| 2              | PA1b.C1.Y25-29.F         |
| 2              | PA1b.C2.low.T            |
| 2              | PA1b.C2.low.M            |
| 2              | PA1b.C2.low.F            |
| 2              | PA1b.C2.med-high.T       |
| 2              | PA1b.C2.med-high.M       |
| 2              | PA1b.C2.med-high.F       |
| 2              | PA1b.C3.une.M            |
| 2              | PA1b.C3.une.F            |
| 2              | PA1b.C3.n.une.M          |
| 2              | PA1b.C3.n.une.F          |
| 2              | PA1b.C3.n.inac.M         |
| 2              | PA1b.C3.n.inac.F         |
| 2              | PA1b.C3.inac.M           |
| 2              | PA1b.C3.inac.F           |
| 2              | PA1b.C4.M                |
| 2              | PA1b.C4.F                |
| 2              | PA1b.C5.M                |
| 2              | PA1b.C5.F                |
| 2              | PA1b.C6.15-24.T          |
| 2              | PA1c.O1.                 |
| 2              | PA1c.S1.Y55_59           |
| 2              | PA1c.S1.Y60-64           |
| 2              | PA1c.S1.M                |
| 2              | PA1c.S1.F                |
| 2              | PA1c.S2.T                |
| 2              | PA1c.S2.M                |
| 2              | PA1c.S2.F                |
| 2              | PA1c.S3.                 |
| 2              | PA1c.S4.                 |
| 2              | PA1c.S5.                 |
| 2              | PA1c.C1.55-74            |
| 2              | PA1c.C2.EMP.W            |
| 2              | PA1c.C2.EMP.M            |
| 2              | PA1c.C3.T                |
| 2              | PA1c.C4.M                |
| 2              | PA1c.C4.F                |
| 2              | PA1c.C5.T                |
| 2              | PA1c.C5.M                |
| 2              | PA1c.C5.F                |
| 2              | PA1c.C6.good             |
| 2              | PA1c.C7.high             |
| 2              | PA1c.C7.med              |
| 2              | PA1c.C7.low              |
| 2              | PA1c.C8.T                |
| 2              | PA1c.C9.M.55-59          |
| 2              | PA1c.C9.F.55-59          |
| 2              | PA1c.C9.M.60-64          |
| 2              | PA1c.C9.F.60-64          |
| 2              | PA1c.C10.T               |
| 2              | PA1c.C10.M               |
| 2              | PA1c.C10.F               |
| 2              | PA1c.C11.T               |
| 2              | PA1c.C12.T               |
| 2              | PA1c.C12.M               |
| 2              | PA1c.C12.F               |
| 2              | PA1c.C13.T               |
| 2              | PA1c.C14.T               |
| 2              | PA1c.C14.M               |
| 2              | PA1c.C14.F               |
| 2              | PA1d.O1.                 |
| 2              | PA1d.S1.M                |
| 2              | PA1d.S1.F                |
| 2              | PA1d.S2.T                |
| 2              | PA1d.S2.M                |
| 2              | PA1d.S2.F                |
| 2              | PA1d.C1.T                |
| 2              | PA1d.C1.M                |
| 2              | PA1d.C1.F                |
| 2              | PA1d.C2.T                |
| 2              | PA1d.C2.M                |
| 2              | PA1d.C2.F                |
| 2              | PA1d.C3.T                |
| 2              | PA1d.C3.M                |
| 2              | PA1d.C3.F                |
| 2              | PA1d.C4.T                |
| 2              | PA1d.C4.M                |
| 2              | PA1d.C4.F                |
| 2              | PA1d.C5.T                |
| 2              | PA1d.C5.M                |
| 2              | PA1d.C5.F                |
| 2              | PA1d.C6.T                |
| 2              | PA1d.C6.M                |
| 2              | PA1d.C6.F                |
| 3              | PA2a.O1.                 |
| 3              | PA2a.S1.Y15-24           |
| 3              | PA2a.S1.Y25-54           |
| 3              | PA2a.S1.Y55-64           |
| 3              | PA2a.S2.M                |
| 3              | PA2a.S2.F                |
| 3              | PA2a.S3.                 |
| 3              | PA2a.S4.                 |
| 3              | PA2a.S5.                 |
| 3              | PA2a.S6.T                |
| 3              | PA2a.S6.Y15-24           |
| 3              | PA2a.S6.M                |
| 3              | PA2a.S6.F                |
| 3              | PA2a.C1.temp             |
| 3              | PA2a.C2.REG              |
| 3              | PA2a.C3.TEMP             |
| 3              | PA2a.C4.T                |
| 3              | PA2a.C4.M                |
| 3              | PA2a.C4.F                |
| 3              | PA2a.C5.T                |
| 3              | PA2a.C5.M                |
| 3              | PA2a.C5.F                |
| 3              | PA2b.O1.                 |
| 3              | PA2b.S1.                 |
| 3              | PA2b.S2.                 |
| 3              | PA2b.S3.                 |
| 3              | PA2b.S4.Y15_64           |
| 3              | PA2b.S4.Y15_24           |
| 3              | PA2b.S4.Y25_54           |
| 3              | PA2b.S4.Y55_64           |
| 3              | PA2b.S5.                 |
| 3              | PA2b.S6.                 |
| 3              | PA2b.S7.                 |
| 3              | PA2b.S8.                 |
| 3              | PA2b.C1.TEMP             |
| 3              | PA2b.C1.REG              |
| 3              | PA2b.C2.ch               |
| 4              | PA3.O1.                  |
| 4              | PA3.S1.                  |
| 4              | PA3.S2.                  |
| 4              | PA3.S3.                  |
| 4              | PA3.S4.                  |
| 4              | PA3.S5.                  |
| 4              | PA3.C1.                  |
| 4              | PA3.C4.                  |
| 4              | PA3.C6.                  |
| 4              | PA3.C7.2                 |
| 4              | PA3.C7.4                 |
| 4              | PA3.C7.5                 |
| 4              | PA3.C7.6                 |
| 4              | PA3.C7.7                 |
| 4              | PA4.1.O1.                |
| 4              | PA4.1.S1.                |
| 4              | PA4.1.S2.A1              |
| 4              | PA4.1.S2.A1_2DCH         |
| 4              | PA4.1.S2.A2              |
| 4              | PA4.1.S2.A2_2DCH         |
| 4              | PA4.1.S3.A1              |
| 4              | PA4.1.S3.A1_2DCH         |
| 4              | PA4.1.S3.A2              |
| 4              | PA4.1.S3.A2_2DCH         |
| 4              | PA4.1.C2.                |
| 4              | PA4.1.C3.                |
| 4              | PA4.1.C4.                |
| 4              | PA4.2.O1.                |
| 4              | PA4.2.S1.                |
| 4              | PA4.2.S2.                |
| 4              | PA4.2.S3.T               |
| 4              | PA4.2.S4.                |
| 4              | PA4.2.S5.                |
| 5              | PA5.O1.                  |
| 5              | PA5.S1.INAC              |
| 5              | PA5.S1.PT                |
| 5              | PA5.S1.M                 |
| 5              | PA5.S1.F                 |
| 5              | PA5.S2.                  |
| 5              | PA5.S3.T                 |
| 5              | PA5.S3.<30               |
| 5              | PA5.S3.>30               |
| 5              | PA5.S4.T                 |
| 5              | PA5.S4.<30               |
| 5              | PA5.S4.>30               |
| 5              | PA5.S5.                  |
| 5              | PA5.S6.                  |
| 5              | PA5.C1.M                 |
| 5              | PA5.C1.F                 |
| 5              | PA5.C2.M                 |
| 5              | PA5.C2.F                 |
| 5              | PA5.C3.M                 |
| 5              | PA5.C3.F                 |
| 5              | PA6a.O1.                 |
| 5              | PA6a.S1.M                |
| 5              | PA6a.S1.F                |
| 5              | PA6a.S2.AGRI             |
| 5              | PA6a.S2.IND              |
| 5              | PA6a.S2.CONSTR           |
| 5              | PA6a.S2.SERV             |
| 5              | PA6a.S3.                 |
| 5              | PA6a.S4.                 |
| 5              | PA6a.S5.                 |
| 5              | PA6a.S6.                 |
| 5              | PA6a.C1.SH.AGRI          |
| 5              | PA6a.C1.SH.IND           |
| 5              | PA6a.C1.SH.CONSTR        |
| 5              | PA6a.C1.SH.G_I           |
| 5              | PA6a.C1.SH.J_L           |
| 5              | PA6a.C1.SH.M_N           |
| 5              | PA6a.C1.SH.O-Q           |
| 5              | PA6a.C1.SH.R_U           |
| 5              | PA6a.C2.15-64            |
| 5              | PA6a.C2.15-24            |
| 5              | PA6a.C2.25-54            |
| 5              | PA6a.C2.55-64            |
| 5              | PA6a.C4.                 |
| 5              | PA6a.C5.                 |
| 5              | PA6b.O1.                 |
| 5              | PA6b.S1.                 |
| 5              | PA6b.S2.                 |
| 5              | PA6b.S4.                 |
| 5              | PA6b.C2.                 |
| 6              | PA7.1.O1.                |
| 6              | PA7.1.S1.Y20-29          |
| 6              | PA7.1.S1.Y30-54          |
| 6              | PA7.1.S1.Y55-64          |
| 6              | PA7.1.S2.F               |
| 6              | PA7.1.S3.M               |
| 6              | PA7.1.S3.F               |
| 6              | PA7.1.S4.                |
| 6              | PA7.1.S5.                |
| 6              | PA7.1.S6.                |
| 6              | PA7.1.C1.                |
| 6              | PA7.1.C2.                |
| 6              | PA7.1.C4.                |
| 6              | PA7.1.C5.                |
| 6              | PA7.1.C6.                |
| 6              | PA7.2.O1.                |
| 6              | PA7.2.S1.M               |
| 6              | PA7.2.S1.F               |
| 6              | PA7.2.S2.M               |
| 6              | PA7.2.S2.F               |
| 6              | PA7.2.S3.                |
| 6              | PA7.2.S4.                |
| 6              | PA7.2.C1.                |
| 6              | PA7.2.C3.                |
| 6              | PA7.2.C4.                |
| 7              | PA8.1.O1.                |
| 7              | PA8.1.S1.MED             |
| 7              | PA8.1.S1.HIGH            |
| 7              | PA8.1.S2.                |
| 7              | PA8.1.S3.                |
| 7              | PA8.1.S4.                |
| 7              | PA8.1.S5.                |
| 7              | PA8.1.S6.                |
| 7              | PA8.1.C1.M               |
| 7              | PA8.1.C1.F               |
| 7              | PA8.1.C1.Y25-34          |
| 7              | PA8.1.C1.Y35-44          |
| 7              | PA8.1.C4.                |
| 7              | PA8.1.C5.                |
| 7              | PA8.2.O1.                |
| 7              | PA8.2.S1.                |
| 7              | PA8.2.S2.                |
| 7              | PA8.2.S3.                |
| 7              | PA8.2.S4.                |
| 7              | PA8.2.S5.                |
| 7              | PA8.2.C1.Y25-64.M        |
| 7              | PA8.2.C1.Y25_64.T        |
| 7              | PA8.2.C1.Y25-34.T        |
| 7              | PA8.2.C1.Y25-34.M        |
| 7              | PA8.2.C1.Y25-34.F        |
| 7              | PA8.2.C1.Y35-44.T        |
| 7              | PA8.2.C1.Y35-44.M        |
| 7              | PA8.2.C1.Y35-44.F        |
| 7              | PA8.2.C1.Y45-54.T        |
| 7              | PA8.2.C1.Y45-54.M        |
| 7              | PA8.2.C1.Y45-54.F        |
| 7              | PA8.2.C1.Y55-64.T        |
| 7              | PA8.2.C1.Y55-64.M        |
| 7              | PA8.2.C1.Y55-64.F        |
| 7              | PA9.1.O1.                |
| 7              | PA9.1.S1.                |
| 7              | PA9.1.S2.n.              |
| 7              | PA9.1.S2.                |
| 7              | PA9.1.S3.                |
| 7              | PA9.1.S4.                |
| 7              | PA9.1.S5.                |
| 7              | PA9.1.S6.                |
| 7              | PA9.1.C1.M               |
| 7              | PA9.1.C1.F               |
| 7              | PA9.1.C1.NAT             |
| 7              | PA9.1.C1.EU27_2020       |
| 7              | PA9.1.C1.NONEU27_2020    |
| 7              | PA9.1.C1.SAME            |
| 7              | PA9.1.C1.OTHEREU27_2020  |
| 7              | PA9.1.C1.OUTEU27_2020    |
| 7              | PA9.1.C2.n.NEET.M        |
| 7              | PA9.1.C2.n.NEET.F        |
| 7              | PA9.1.C2.NEET.M          |
| 7              | PA9.1.C2.NEET.F          |
| 7              | PA9.1.C3.M               |
| 7              | PA9.1.C3.F               |
| 7              | PA9.1.C4.M               |
| 7              | PA9.1.C4.F               |
| 7              | PA9.2.O1.                |
| 7              | PA9.2.S1.READ            |
| 7              | PA9.2.S1.MATH            |
| 7              | PA9.2.S1.SCIE            |
| 7              | PA9.2.S2.                |
| 7              | PA9.2.S3.                |
| 7              | PA9.2.S4.                |
| 7              | PA9.2.S5.                |
| 7              | PA9.2.C1.HIGH.M          |
| 7              | PA9.2.C1.HIGH.F          |
| 7              | PA9.2.C1.NAT             |
| 7              | PA9.2.C1.EU27_2020       |
| 7              | PA9.2.C1.NONEU27_2020    |
| 7              | PA9.2.C1.SAME            |
| 7              | PA9.2.C1.OTHEREU27_2020  |
| 7              | PA9.2.C1.OUTEU27_2020    |
| 7              | PA9.2.C2.M               |
| 7              | PA9.2.C2.F               |
| 7              | PA9.2.C3.M               |
| 7              | PA9.2.C3.F               |
| 7              | PA9.2.C4.                |
| 7              | PA10.O1.                 |
| 7              | PA10.S1.                 |
| 7              | PA10.S2.                 |
| 7              | PA10.C1.                 |
| 7              | PA10.C2.                 |
| 8              | PA11.O1.                 |
| 8              | PA11.S1.                 |
| 8              | PA11.S2.                 |
| 8              | PA11.S3.T                |
| 8              | PA11.S3.M                |
| 8              | PA11.S3.F                |
| 8              | PA11.S4.                 |
| 8              | PA11.S5.                 |
| 8              | PA11.S6.                 |
| 8              | PA11.S8.                 |
| 8              | PA11.S9.                 |
| 8              | PA11.S10.                |
| 8              | PA11.S11.                |
| 8              | PA11.S12.                |
| 8              | PA11.S13.                |
| 8              | PA11.S14.                |
| 8              | PA11.S15.                |
| 8              | PA11.C1.                 |
| 8              | PA11.C2.                 |
| 8              | PA11.C3.n.M              |
| 8              | PA11.C3.n.F              |
| 8              | PA11.C4.T                |
| 8              | PA11.C4.M                |
| 8              | PA11.C4.F                |
| 8              | PA11.C5.T                |
| 8              | PA11.C5.1                |
| 8              | PA11.C5.2                |
| 8              | PA11.C5.3                |
| 8              | PA11.C5.4                |
| 8              | PA11.C5.5                |
| 8              | PA11.C5.6                |
| 8              | PA11.C5.7                |
| 8              | PA11.C5.8                |
| 8              | PA11.C5.9                |
| 8              | PA11.C5.10               |
| 8              | PA11.C5.11               |
| 8              | PA11.C6.                 |
| 8              | PA11.C7.                 |
| 8              | PA11.C8.M                |
| 8              | PA11.C8.F                |
| 8              | PA11.C9.M                |
| 8              | PA11.C9.F                |
| 8              | PA11.C11.T               |
| 8              | PA11.C11.Q1              |
| 8              | PA11.C11.Q2              |
| 8              | PA11.C11.Q3              |
| 8              | PA11.C11.Q4              |
| 8              | PA11.C11.Q5              |
| 8              | PA11.C12.                |
| 9              | PA11a.O1.                |
| 9              | PA11a.S1.                |
| 9              | PA11a.S2.                |
| 9              | PA11a.S3.                |
| 9              | PA11a.S4.                |
| 9              | PA11a.S5.                |
| 9              | PA11a.S6.                |
| 9              | PA11a.S7.                |
| 9              | PA11a.S8.                |
| 9              | PA11a.S9.                |
| 9              | PA11a.S10.               |
| 9              | PA11a.C1.ATWORK          |
| 9              | PA11a.C1.NOTWORK         |
| 9              | PA11a.C2.1               |
| 9              | PA11a.C2.2               |
| 9              | PA11a.C2.3               |
| 9              | PA11a.C2.4               |
| 9              | PA11a.C2.5               |
| 9              | PA11a.C2.6               |
| 9              | PA11a.C3.                |
| 9              | PA11a.C4.                |
| 9              | PA11b.O1.                |
| 9              | PA11b.S1.T               |
| 9              | PA11b.S1.M               |
| 9              | PA11b.S1.F               |
| 9              | PA11b.S2.                |
| 9              | PA11b.S3.                |
| 9              | PA11b.S4.                |
| 9              | PA11b.S5.T               |
| 9              | PA11b.S5.M               |
| 9              | PA11b.S5.F               |
| 9              | PA11b.S6.                |
| 9              | PA11b.S7.                |
| 9              | PA11b.S8.                |
| 9              | PA11b.S9.                |
| 9              | PA11b.S10.               |
| 9              | PA11b.S11.               |
| 9              | PA11b.S12.               |
| 9              | PA11b.C4.                |
| 9              | PA11b.C5.UNE             |
| 9              | PA11b.C5.INAC            |
| 9              | PA11b.C6.T               |
| 9              | PA11b.C6.Q1              |
| 9              | PA11b.C6.Q2              |
| 9              | PA11b.C6.Q3              |
| 9              | PA11b.C6.Q4              |
| 9              | PA11b.C6.Q5              |
| 9              | PA11c.O1.                |
| 9              | PA11c.S1.T               |
| 9              | PA11c.S1.M               |
| 9              | PA11c.S1.F               |
| 9              | PA11c.S2.T               |
| 9              | PA11c.S2.M               |
| 9              | PA11c.S2.F               |
| 9              | PA11c.S3.                |
| 9              | PA11c.S4.                |
| 9              | PA11c.S5.                |
| 9              | PA11c.S6.                |
| 9              | PA11c.S7.                |
| 9              | PA11c.S8.                |
| 9              | PA11c.C1.                |
| 9              | PA11c.C2.                |
| 9              | PA11c.C6.M               |
| 9              | PA11c.C6.F               |
| 9              | PA11c.C7.                |
' %>% 
  readMarkDownTable() %>% 
  .[, CompendiumNum := as.integer(CompendiumNum)] %>% 
  .[, JAF_KEY := JAF_KEY %>% sub('^(PA11\\.C3)\\.n(\\..)$','\\1\\2',.)] %>% # remove n from PA11.C3.n.M and PA11.C3.n.F
  merge(JAF_NAMES_DESCRIPTIONS, by='JAF_KEY') %>% 
  .[, `Policy Area` := sub('$PA(.+)\\..*$','\\1',.)] %>% 
  .[, Indicator := name] %>% 
  .[, name := NULL] %>% 
  .[, Compendium := 
      paste0("=HYPERLINK(",
             dq("[Compendium-",CompendiumNum,".xlsx]",sq(JAF_KEY),"!A1"),
             ",",
             dq("Compendium - ",CompendiumNum),
             ")")]


# Actions -----------------------------------------------------------------



